### PR TITLE
major overhaul

### PR DESCRIPTION
**Pull request by ZanzyTHEbar**
- add CLI and semantic versioning
- add auto-push to registry
- restructure project to support a proper library
- added release and debug environments

### CODE REVIEW

**Comment by ZanzyTHEbar** [comment]
This is a much-needed overhaul if you plan on having the library on the registry. Happy to contribute. 

One thing you will need to do, that i can't do, is add your pio account API Token to your repos github secrets. 

Navigate to `Settings > Secrets` Create a new secret. Then, open pio in vscode, go to your `account > Token`, grab your token. Put the token as the secret value and put the name as `PLATFORMIO_AUTH_TOKEN`

**Comment by sagaert** [comment]
Hi @ZanzyTHEbar,
thanks a lot for your input. I'm just working on the code and on a GitHub action for the auto-push so i can use your input well.
I'm a little confused about the structure in your PR because it differs from the structure described in the [PIO Docs](https://docs.platformio.org/en/latest/librarymanager/creating.html)

**Comment by ZanzyTHEbar** [comment]
Ah, you mean because i am using the `lib` folder. The docs recommended way is one way to do it - not the only way, and not the way i would recommend. its a simple intro way that uses the traditional C-Style structure. Using the `lib` folder is a more structured and neater way to do it. All files are in their own sub folder, no need to have files spread around in two separate folders. Its the more cpp style of doing things.

**Comment by sagaert** [comment]
Ah, ok. And that is also why the header file was moved from include to src ?

**Comment by ZanzyTHEbar** [comment]
> Ah, ok. And that is also why the header file was moved from include to src ?

the header file was moved into its own directory - same with cpp file. `/lib/esp32_config_library/src` In the `src` folder of the library you can then nest as many sub folders as you wish.

**Comment by ZanzyTHEbar** [comment]
image

**Comment by ZanzyTHEbar** [comment]
I added the `.h` and `.hpp` for support for people who are used to cpp files and C files. `h` is a c file, compatible with Cpp - but people who are used to cpp will grab `hpp` by habit as well. Just a small detail :) totally optional.

**Comment by sagaert** [comment]
Thanks for your ideas, that really helps.
You suggest to put the main.cpp in the src Folder. The content will be an example for using it. In my (yet not pushed) local repo, i put it into a folder called examples. Does this make sense ?

**Comment by ZanzyTHEbar** [comment]
For custom libraries you can make an examples folder and put example files in there - but the `main.cpp` _has_ to go in `src` unless you change the src directory that pio will look for - but then if you have more than one example in that folder you will run into build issues. So dont do that. Imo, keep the structure in the image i sent- but add an examples folder with a copy of `main.cpp`. Then you can add as many example files as you want. Here is one of my [libraries](https://github.com/ZanzyTHEbar/EasyNetworkManager) as an example.

**Comment by ZanzyTHEbar** [comment]
i tested builld btw- this pr is fully compatible and doesnt break anything. So feel free to accept and make changes as needed - you can always revert should you wish - but the pr does build :) just fine

**Comment by sagaert** [comment]
Thanks for your support :-)

**Comment by ZanzyTHEbar** [comment]
> Thanks for your support :-)

no problem, question is there a reason you are using arduino String class? 

On the esp32 and esp8266 you have full C++ STL support and there is another string type `std::string` which i highly recommend you switch to. It supports something called Small String Optimization (SSR) - which yields greater performance, less heap usage, and more stability. Arduino String class should really be avoided at all costs. Its great for new-people or one-off projects but not for a library - can cause heap fragmentation and just has overall poor performance.

**Comment by ZanzyTHEbar** [comment]
I am going to watch development of this - as i like the initial logic structure you have for interfacing with preferences, i intend on adding this to one of my libraries to replace my current preferences interface. Nothing wrong with mine, it works great- but i like how dynamic you are making yours. Good setup with the concept of a namespace class.

**Comment by ZanzyTHEbar** [comment]
@sagaert Also - check  this out, if you dont want to maintain a copy for some of your examples. [Docs for library.json](https://docs.platformio.org/en/latest/manifests/library-json/fields/examples.html)

**Comment by sagaert** [comment]
@ZanzyTHEbar There is some refactoring upcoming this week and i plan to post a first version (1.0.0) untile the end of january.

**Comment by sagaert** [comment]
@ZanzyTHEbar I just released the first version (1.0.0) of the library with a working wifi / web server interface. In further versions a CLI will be added to be used with usb or bluetooth terminal.

**Pull request merged**
